name: parquet_content_pump
services:
  psql:
    container_name: psql
    build:
      context: ./db
      dockerfile: Dockerfile
    volumes:
      - psql_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=metabase
      - POSTGRES_DB=metabase
    healthcheck:
      test:
        [
          "CMD-SHELL", "pg_isready -d metabase -U metabase"
        ]
      interval: 5s
      timeout: 5s
      retries: 5

  minio:
    container_name: minio
    image: minio/minio:latest
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - minio_datastore:/data
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: server /data --console-address ":9001"

  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio:9000 minio minio123;
      /usr/bin/mc mb myminio/daily;
      /usr/bin/mc anonymous set public myminio/daily;
      exit 0;
      "
volumes:
    psql_data: {}
    minio_datastore: {}
