[tool.poetry]
name = "fastapi-polars"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.13"
fastapi = "^0.115.6"
polars = "^1.17.1"
uvicorn = "^0.34.0"
pyarrow = "^18.1.0"
locust = "^2.32.4"
polyfactory = "^2.18.1"
uvloop = "^0.21.0"
httptools = "^0.6.4"
granian = "^1.7.1"
fsspec = "^2024.12.0"
s3fs = "^2024.12.0"
pydantic-settings = "^2.7.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
