"""add books_index

Revision ID: 3d8cfce720df
Revises: cf35258f1403
Create Date: 2025-03-13 13:44:41.318868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d8cfce720df'
down_revision: Union[str, None] = 'cf35258f1403'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books_index',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('isbn', sa.String(length=17), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('parquet_uuid', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['parquet_uuid'], ['parquet_index.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('isbn')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('books_index')
    # ### end Alembic commands ###
