"""init

Revision ID: 52223f807996
Revises: 
Create Date: 2025-04-06 16:16:19.205981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52223f807996'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parquet_index',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('s3_url', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('s3_url')
    )
    op.create_table('books_index',
    sa.Column('isbn', sa.Text(), nullable=False),
    sa.Column('pages', sa.BigInteger(), nullable=True),
    sa.Column('author', sa.Text(), nullable=True),
    sa.Column('pub_date', sa.Date(), nullable=True),
    sa.Column('pid', sa.BigInteger(), nullable=True),
    sa.Column('hash', sa.BigInteger(), nullable=False),
    sa.Column('parquet_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['parquet_id'], ['parquet_index.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('hash')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('books_index')
    op.drop_table('parquet_index')
    # ### end Alembic commands ###
