"""add new columns to books_index

Revision ID: c625e5ce34b7
Revises: 3d8cfce720df
Create Date: 2025-03-14 13:53:07.570662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c625e5ce34b7'
down_revision: Union[str, None] = '3d8cfce720df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books_index', sa.Column('pages', sa.Integer(), nullable=False))
    op.add_column('books_index', sa.Column('author', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books_index', 'author')
    op.drop_column('books_index', 'pages')
    # ### end Alembic commands ###
